# Generated by Django 3.0.3 on 2020-10-04 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_article_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='thumbnail',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=''),
        ),
    ]
