# Generated by Django 3.0.3 on 2020-10-04 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_remove_article_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='thumb',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
